/*
# Test the Server API
*/
@host http://localhost:8080
###
# @name produce
GET /api/produce

HTTP/1.1 200  - OK
x-powered-by: Express
access-control-allow-origin: *
content-type: application/json; charset=utf-8
content-length: 4099
etag: W/"1003-h3rAE87RuPWhcpiwW7ErpZccsAU"
date: Mon, 07 Apr 2025 15:03:41 GMT
connection: close
###
# @ref produce
GET /api/produce/{{ produce[produce.length -1]._id }}

HTTP/1.1 200  - OK
x-powered-by: Express
access-control-allow-origin: *
content-type: application/json; charset=utf-8
content-length: 210
etag: W/"d2-Vo9XEF9pRM0KqR8yyYD6PfqX7MA"
date: Mon, 07 Apr 2025 15:04:02 GMT
connection: close